# Copyright (c) 2021, 2022 Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
# 
---
- hosts: localhost
  collections:
    - oracle.oci
  tasks:
    - name: Check pre-requisites
      fail:
        msg: "Environment variable {{item}} not set. Please declare an environment variable with an appropriate value for the sample to work."
      when: item not in ansible_env
      with_items:
        - "compartment_ocid"

    - name: Create a local scratch folder
      ansible.builtin.file:
        path: ./mgmt_gateway_scratch
        state: directory
        mode: '0755'

    - name: Create management gateway install key
      oci_management_agent_install_key:
        # required
        compartment_id: "{{compartment_ocid}}"
        display_name:  "{{mgmt_gateway_install_key_name}}"
        # optional
        #allowed_key_install_count: 56
        #time_expires: time_expires_example
        is_unlimited: true
      register: key_result
    - debug: 
        msg="{{key_result.management_agent_install_key}}"
    - set_fact:
        management_gateway_install_key: "{{key_result.management_agent_install_key.key}}"

    - name: Create management gateway response file
      copy:
        content: "######################################################################## \n
        # Please refer the following Management gateway Installation Guide for more details. \n
        # \n
        # https://docs.cloud.oracle.com/iaas/management-gateways/index.html  \n
        #\n
        # Since this file has sensitive information, please make sure that after \n
        # executing setup.sh you either delete this file or store it in a secure \n
        # location. \n
        # \n
        ######################################################################## \n
        managementAgentInstallKey = {{management_gateway_install_key}} \n
        #CredentialWalletPassword = \n 
        AgentDisplayName = \n
        #Please uncomment the below tags properties and provide values as needed \n
        #FreeFormTags = [{\"<key1>\":\"<value1>\"}, {\"<key2>\":\"<value2>\"}]\n
        #DefinedTags = [{\"namespace1\":{\"<key1>\":\"<value1>\"}}, {\"namespace2\":{\"<key2>\":\"<value2>\"}}]\n
        #GatewayPort = \n
        #GatewayUsername = \n
        #GatewayPassword = \n
        #ProxyHost = \n
        #ProxyPort = \n
        #ProxyUser = \n
        #ProxyPassword = \n
        #ProxyRealm = \n
        #GatewayCertOcid = \n "
        dest: ./mgmt_gateway_scratch/input.rsp
    
    - name: List management gateway images
      oci_management_agent_image_facts:
        compartment_id: "{{compartment_ocid}}"
        install_type: GATEWAY
      register: image_result
    - set_fact:
        object_url: "{{ item.object_url | split('/')}}"
        namespace: "{{[4]|map('extract', item.object_url.split('/')) | join()}}"
        bucket_name: "{{[6]|map('extract', item.object_url.split('/')) | join ()}}"
        object_name: "{{[8,9,10]|map('extract', item.object_url.split('/')) | join('/')}}"
      with_items: "{{image_result.management_agent_images}}"
      when:
        - item.platform_name == "Linux-x86_64"
        - item.package_type == "RPM"
    - debug:
        msg: "Extracted the agent image details as follows Namespace: {{namespace}} Bucket: {{bucket_name}} Object name: {{object_name}}"
  
    - name: Download Management Gateway Package
      oci_object_storage_object:
        # required
        namespace_name: "{{namespace}}"
        bucket_name: "{{bucket_name}}"
        object_name: "{{object_name}}"
        dest: ./mgmt_gateway_scratch/oracle.mgmt_gateway.rpm
      tags: download_agent
  
- hosts: gateway_hosts 
  tasks:    
    - name: Transfer all management gateway files over to the hosts
      become: yes
      become_user: root
      copy:
        src: ./mgmt_gateway_scratch
        dest: /tmp/
        owner: "{{user_with_sudo}}"
        group: "{{user_with_sudo}}"
        mode: '0644'

    - name: Install the management gateway
      become: yes
      become_user: "{{user_with_sudo}}"
      shell: "sudo rpm -ivh {{mgmt_gateway_scratch}}/oracle.mgmt_gateway.rpm"
      register: install_gateway_result
      tags: install_gateway
    - debug: 
        msg: "{{install_gateway_result}}"

    - name: Set up management gateway service
      become: yes
      become_user: "{{user_with_sudo}}"
      shell: "sudo /opt/oracle/mgmt_agent/agent_inst/bin/setupGateway.sh opts={{mgmt_gateway_scratch}}/input.rsp"
      register: result
      tags: setup_gateway
    - debug:
        msg: "Setup Gateway result: {{result}}"
    
    - name: Start management gateway service
      ansible.builtin.service:
        name: mgmt_gateway
        state: started
      tags: start_gateway
    
    - name: Cleanup management gateway scratch
      become: yes
      become_user: "{{user_with_sudo}}"
      file:
        path: "{{mgmt_gateway_scratch}}"
        state: absent